
ci:
  python-version: "3.14"

files:
  version: release.version

bump:
  enabled: true
  base-branch: main
  label: autobump

release:
  full-release: true
  publish: true

deploy:
  auto-dev: false

docker:
  enabled: true
  image-name: fsamp-processor
  dockerfile: Dockerfile.lambda
  registry: ghcr.io
  platforms: linux/arm64
  runner: ubuntu-24.04-arm

sonar:
  enabled: true
  organization: pauszek
  project-key: pauszek_fsamp-processor
