name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

jobs:
  call-python:
    uses: pauszek/fsamp-code-ci/.github/workflows/build-python.yml@v0.0.18
    secrets: inherit
