name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

jobs:
  call-python:
    uses: pauszek/fsamp-code-ci/.github/workflows/build-python.yml@404e1dad7df2f2d5505e64fa4b26104e51f54b24
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GABRBA_SECRET: ${{ secrets.GABRBA_SECRET }}
